apiVersion: v1
kind: Service
metadata:
  name: {{ include "zkwasm-exchange.fullname" . }}-redis
  labels:
    {{- include "zkwasm-exchange.labels" . | nindent 4 }}
spec:
  ports:
    - port: {{ .Values.config.redis.port }}
      targetPort: {{ .Values.config.redis.port }}
      protocol: TCP
      name: redis
  selector:
    app: {{ include "zkwasm-exchange.fullname" . }}-redis
