apiVersion: v1
kind: Service
metadata:
  name: {{ include "zkwasm-automata.fullname" . }}-merkle
  labels:
    {{- include "zkwasm-automata.labels" . | nindent 4 }}
spec:
  ports:
    - port: {{ .Values.config.merkle.port }}
      targetPort: {{ .Values.config.merkle.port }}
      protocol: TCP
      name: http
  selector:
    app: {{ include "zkwasm-automata.fullname" . }}-merkle
