name: CI/CD Pipeline

on:
  push:
    branches: [ main ]
    tags: [ 'v*' ]

env:
  REGISTRY: ghcr.io
  IMAGE_NAME: ${{ github.repository }}

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest
    permissions:
      contents: read
      packages: write

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3
        with:
          buildkitd-flags: --debug

      - name: Convert to lowercase
        id: lowercase
        run: |
          echo "REPO_LOWER=${GITHUB_REPOSITORY,,}" >> $GITHUB_ENV

      - name: Log into registry
        uses: docker/login-action@v3
        with:
          registry: ${{ env.REGISTRY }}
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}

      - name: Extract metadata
        id: meta
        uses: docker/metadata-action@v5
        with:
          images: ${{ env.REGISTRY }}/${{ env.REPO_LOWER }}
          tags: |
            type=raw,value=latest
            type=ref,event=branch
            type=ref,event=pr
            type=semver,pattern={{version}}
            type=sha,format=long

      - name: Ensure .env file exists
        run: |
          if [ ! -f .env ]; then
            echo "Creating default .env file"
            echo "BUILD_MODE=production" > .env
          fi
          echo "Current .env file contents:"
          cat .env

      - name: Build and push image
        uses: docker/build-push-action@v5
        with:
          context: .
          push: ${{ github.event_name != 'pull_request' }}
          file: Dockerfile.ci
          tags: ${{ steps.meta.outputs.tags }}
          labels: ${{ steps.meta.outputs.labels }}
          no-cache: true

      - name: Generate image info
        if: success() && github.event_name != 'pull_request'
        run: |
          echo "Image built and pushed successfully"
          echo "Image: ${{ env.REGISTRY }}/${{ env.REPO_LOWER }}"
          echo "Tags: ${{ steps.meta.outputs.tags }}"
          
          echo "Using pre-built WASM files from build-artifacts directory"
          if [ -f build-artifacts/wasm.md5 ]; then
            echo "WASM MD5 from build-artifacts: $(cat build-artifacts/wasm.md5)"
          else
            echo "Warning: build-artifacts/wasm.md5 file not found"
          fi

      - name: Notify build result
        if: always()
        run: |
          echo "Image built and pushed: ${{ env.REGISTRY }}/${{ env.REPO_LOWER }}"
          echo "Build status: ${{ job.status }}"